language: erlang
otp_release:
  - 18.0
  - 17.3
  - 17.1
  - 17.0
  - R16B03-1
  - R16B02
  - R16B01
  - R16B

sudo: false

before-install:
  - sudo apt-get install wget curl
install:
  - ./rebar3 do update, compile
script:
  - ./priv/ci/run_tests.sh
